modLoader = "javafml"
loaderVersion = "[43,)"
license="${mod_license}"

[[mods]]
modId = "filtpick_additions"
displayTest="MATCH_VERSION"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = '''
${mod_description}
'''
itemIcon = "minecraft:netherite_sword"

[[dependencies.filtpick_additions]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.filtpick_additions]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2]"
ordering = "NONE"
side = "BOTH"